### PR TITLE
负面AI判定

### PR DESCRIPTION
**Pull request by PythonSmall-Q**
maybe有bug，看看再说

你看看有没有bug我没有测试过 @boomzero 

有问题直接改，我大概率不会上电脑

### CODE REVIEW

**Comment by boomzero** [comment]
没必要吧, 我短消息就不能发 `No`了? 查的太严了, badge可以因为badge短

**Review by boomzero — CHANGES_REQUESTED** [review]
Create an RFC before making a change like this, thanks.

**Comment by PythonSmall-Q** [comment]
那你close了吧
















At 2024-07-09 22:30:56, "Zhu Chenrui" ***@***.***> wrote:

@boomzero requested changes on this pull request.

Create an RFC before making a change like this, thanks.

**Comment by boomzero** [comment]
closed as requested

**Pull request closed without merging**
