### PR TITLE
用户可以申请关闭私信接收

### PR DESCRIPTION
**Pull request by PythonSmall-Q**

### CODE REVIEW

**Review by boomzero — CHANGES_REQUESTED** [review]
在Script 里关掉短消息提醒不就完了

**Review by boomzero — APPROVED** [review]

**Comment by boomzero** [comment]
> _ No description provided. _

@PythonSmall-Q next time, fill out the entire template, or your PR will be closed

**Comment by boomzero** [comment]
The PR template is incredibly will written and it is important

**Comment by PythonSmall-Q** [comment]
我发的时候是你create PR template的5个小时前

**Comment by boomzero** [comment]
> 我发的时候是你create PR template的5个小时前 Message ID: ***@***.***>

I see

**Pull request merged**
